### ISSUE TITLE
FinerGitRewriterで構築したリポジトリのHEADのファイルはすべて削除されている

### ISSUE THREAD

**Issue by YoshikiHigo** [kusumotolab/FinerGit#112]
FinerGitRewriterでリポジトリを構築すると，HEADのファイルがすべて削除されている状態になっている．
`git reset --hard`すれば正常な状態に戻る．

**Comment by sh5i** [comment]
リポジトリ構築後にHEADをcheckoutし直す処理の追加が必要．
