### ISSUE TITLE
ファイルフォーマットが統一されていない

### ISSUE THREAD

**Issue by YoshikiHigo** [kusumotolab/FinerGit#115]
現時点では，例えば，import文で空行の有無の違い等が発生しています．
僕は，以下のフォーマットを利用しています．
https://github.com/google/styleguide/blob/gh-pages/eclipse-java-google-style.xml
もし差し支えなければ，同じフォーマットにしていただけるとしょうもない差分はなくなるかな，と思いました．

関連して，jp.ac.titech.c.se.stein.coreパッケージ以下は，他のリポジトリからコピーしてきたファイルですよね？
このパッケージ以下については，僕が修正を直接しないということでよいでしょうか．

**Comment by sh5i** [comment]
なるべく差分をつくらないようにしていたのですが，先日の最後のコミットではフォーマットされてしまっていました，すみません．指定のフォーマットを使うようにします．

**Comment by sh5i** [comment]
該当パッケージは他ライブラリ（https://github.com/sh5i/git-stein）からのコピーで，このライブラリはアプリケーション独立のリポジトリ変換という形で保ちたいと考えています．その範囲内で，ライブラリ側に機能を組み込んでから移植という形をとって構わないのでしたら，該当パッケージの変更については私が承るということで構いません．（必要でしたら，上記の設定に従ったフォーマット等を行うぶんには問題ありません）

**Comment by YoshikiHigo** [comment]
ありがとうございます．よろしくお願いします．
フォーマットはそのままで問題ありません．
