### ISSUE TITLE
フィールドを表すファイルの拡張子がajavaなのはわかりにくい

### ISSUE THREAD

**Issue by YoshikiHigo** [kusumotolab/FinerGit#130]
以下の拡張子に変更するのはどうか？
ファイル：.javafile
クラス：.javaclass
メソッド：.javamethod
フィールド：.javafield

**Comment by YoshikiHigo** [comment]
@sh5i 上記の方針でどうでしょうか？もしもっとよいアイデアあれば教えてください．

**Comment by sh5i** [comment]
妙案はないです，ごめんなさい．長くなる+長さが変わるのが気になりますが，わかりやすさを優先するのであれば，上記のように変えてよいと思います．

**Comment by YoshikiHigo** [comment]
はい，わかりやすさ優先にしたいと思います．
長さが変わるというのは拡張子の長さが統一されていないってことですよね．これはしょうがないかなと．．．

**Comment by YoshikiHigo** [comment]
んー，やっぱりださいですね．
クラスの外側を表すファイルは存在価値が一番低いと思うので，その名前がわかりにくくなるのがフィールドを表すファイルがわかりにくくなるよりもましだと思いました．

**Comment by YoshikiHigo** [comment]
ファイル：.pjava （ファイル　→　ファイ　→　φ　→　phi　→　p）（他に思いつかない．．．）
クラス：.cjava
インターフェース：.ijava
メソッド：.mjava
フィールド：.fjava
にしようと思います．

**Comment by sh5i** [comment]
w: whole, p: persistant, s: stored, o: outer (of class decl.), s: surround 等を思いつきました．
なお，クラスとインタフェースは敢えて分けなくてもいいのではないか，と個人的には思いました．

**Comment by YoshikiHigo** [comment]
wholeはなんだか全部含んでそうな気がします．
囲んでいると言うよりは外側という感じがするので，surroundよりはouterかな，と思います．
outerは良さそうですね．
周辺を表すperipheralでも良さそうに思いました．
persistentやstoredはdb関係っぽいイメージがしました．

**Comment by YoshikiHigo** [comment]
クラスとインターフェースの分離は，クラスとインターフェースがファイル名でわかる利便性よりも，拡張子が増えることによる煩雑性の方が大きいですかね．ちゃんとするとなると，enumを表すejavaやアノテーションを表すajavaが必要になってくるような気もしますね．

**Comment by sh5i** [comment]
はい，enum や annotation を増やしていくよりは，名前空間としては Type なので単一でよいのではないかと感じました（ただし，だからといって tjava にはしなくていいと思っています）．

**Comment by YoshikiHigo** [comment]
なるほど，そうですね．その方針にしましょう．
ファイルについては，クラスの外側は情報としては保存しているけど，主ではないということを名前に入れるという意味で，とりあえずはperipheralのpにしたいと思います．
まとめると以下のようになります．
ファイル：.pjava 
クラス（インターフェース等も含めて）：.cjava
メソッド：.mjava
フィールド：.fjava

**Comment by sh5i** [comment]
はい，よいと思います．pjava なら peripheral とも phi ともとれるのでお得(?)だと思います．
